apiVersion: v1
kind: Service
metadata:
  name: hserviceX
spec:
  ports:
    - port: 3500
      protocol: TCP
      targetPort: 3500
  selector:
    app: cserverX
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hingressX
spec:
  backend:
    serviceName: hserviceX
    servicePort: 3500
